using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;

namespace Resemble
{
    public partial class RessembleSettingsProvider
    {
        private GUIContent pathMethode = new GUIContent("Path methode", "Indicates the method chosen by the plugin to " +
            "provide the save path for clips generated by a CharacterSet");

        private GUIContent useSubFolder = new GUIContent("Use sub folder", "Specifies if you want a folder with the " +
            "name of the CharacterSet before saving the AudioClips.");

        private void DrawPathsSettingsGUI()
        {
            //Description
            GUILayout.Label("Describe where AudioClips from CharacterSets should be generated.", EditorStyles.centeredGreyMiniLabel);
            GUILayout.Space(10);

            //Settings fields
            Settings.instance.pathMethode = (Settings.PathMethode) EditorGUILayout.EnumPopup(
                pathMethode, Settings.instance.pathMethode);
            Settings.instance.useSubFolder = EditorGUILayout.Toggle(useSubFolder, Settings.instance.useSubFolder);


            //Example label
            GUILayout.Space(10);
            GUILayout.Label("Example :");

            //Draw example image
            Rect rect = GUILayoutUtility.GetRect(1, 1);
            Texture image = Resources.instance.pathImages[(int)Settings.instance.pathMethode * 2 + (Settings.instance.useSubFolder ? 1 : 0)];
            rect.Set(rect.x, rect.y, image.width+1, image.height+1);
            GUI.Label(rect, image);
        }

        private void DrawPathsFooterGUI(){}
    }
}
